# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-nbdev-docments',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-nbdev-docments',
                'lib_path': 'cjm_nbdev_docments'},
  'syms': {'cjm_nbdev_docments.core': {'cjm_nbdev_docments.core.foo': ('core.html#foo', 'cjm_nbdev_docments/core.py')}}}
